actions: 6
bottom_right_x: -12
bottom_right_y: -12
decay: 1.0e-06
env_name: SpaceInvaders-v0
eps: 0.1
exploration: greedy
gain: 5
gamma: 0.9
gpu: true
input_shape: !!python/tuple
- 110
- 84
- 4
max_episode_steps: 10000
nstack: 4
path: Policy/
start_from_pretrained: 1
top_left_x: 4
top_left_y: 8
learning_rate: 0.001
Total_Q_Iterations: 50
sample_size: 8000
target_update_iterations: 5
regess_for_epochs: 40